<?php

namespace AppBundle\Entity;
use Doctrine\ORM\Query;

/**
 * ProjectUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserProjects(User $user){
        return $this->createQueryBuilder('pu')
                    ->select("project")
                    ->from("AppBundle:ProjectUser", "projectUser")
                    ->where('pu.user = :user')
                    ->setParameter('user', $user)
                    ->leftJoin("AppBundle:Project", "project", 'WITH', 'pu.project = project.id')
                    ->getQuery()
                    ->getResult();
    }

    public function getProjectUsers($projectId){
        return $this->createQueryBuilder('pu')
            ->select("user")
            ->from("AppBundle:ProjectUser", "projectUser")
            ->where("pu.project = :projectId")
            ->setParameter('projectId', $projectId)
            ->leftJoin("AppBundle:User", "user", 'WITH', "pu.user = user.id")
            ->getQuery()
            ->getResult();
    }

    public function isUserOwner($user, $projectId){
        return $this->createQueryBuilder('pu')
            ->select("pu.owner")
            ->where("pu.user = :user AND pu.project = :project")
            ->setParameter('user', $user)
            ->setParameter('project', $projectId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
